### ISSUE TITLE
group installation does not work on CentOS 6

### ISSUE THREAD

**Issue by ExalDraen** [GeoffWilliams/puppet-package_yum_group#1]
On CentOS 6.6, `yum group <foo>` is not a thing, so the commands in the package provider don't work. 

E.g. 
```
Execution of '/usr/bin/yum group list installed -q' returned 1: No such command: group. Please use /usr/bin/yum --help
```

An easy workaround would be to use the old invocation for this, i.e. `groupinstall` / `grouplist` / etc. in the provider, instead of using `yum group <stuff>`.

**Comment by GeoffWilliams** [comment]
released to puppet forge as v0.1.1
